name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: gcc -o pr pr.c
    - name: Run with argument 3
      run: ./pr 3
    - name: Run with argument 4
      run: ./pr 4
